AWSTemplateFormatVersion: 2010-09-09
Description: openapi-backend-aws-sam
Transform:
- AWS::Serverless-2016-10-31
Resources:
  api:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Runtime: nodejs16.x
      # Architectures: 
      #  - arm64
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
